import {database} from "./db";
import {reportPurposeForStarter,type ReportChangeManifest,type ReportPurpose,type ReportVersionMetadata} from "./duckdive-report";

type Row={workspace_id:string;dive_id:string;version:number;source_hash:string;purpose_json:ReportPurpose;change_manifest_json:ReportChangeManifest;run_id:string|null;created_at:string};
function response(row:Row):ReportVersionMetadata{return {workspaceId:row.workspace_id,diveId:row.dive_id,version:Number(row.version),sourceHash:row.source_hash,purpose:row.purpose_json,manifest:row.change_manifest_json,runId:row.run_id,createdAt:row.created_at};}

export async function getDiveReportVersion(userId:string,diveId:string,version?:number){const sql=database();try{const rows=await sql<Row[]>`SELECT r.workspace_id,r.dive_id,r.version,r.source_hash,r.purpose_json,r.change_manifest_json,r.run_id,r.created_at FROM app.duckdive_report_version r JOIN app.workspace w USING(workspace_id) WHERE w.user_id=${userId}::uuid AND r.dive_id=${diveId} ${version===undefined?sql``:sql`AND r.version=${version}`} ORDER BY r.version DESC LIMIT 1`;return rows[0]?response(rows[0]):null;}finally{await sql.end();}}

export async function getDiveReportVersionForWorkspace(workspaceId:string,diveId:string,version:number){const sql=database();try{const [row]=await sql<Row[]>`SELECT workspace_id,dive_id,version,source_hash,purpose_json,change_manifest_json,run_id,created_at FROM app.duckdive_report_version WHERE workspace_id=${workspaceId}::uuid AND dive_id=${diveId} AND version=${version}`;return row?response(row):null;}finally{await sql.end();}}

export async function saveDiveReportVersion(input:{workspaceId:string;diveId:string;version:number;sourceHash:string;purpose:ReportPurpose;manifest:ReportChangeManifest;runId?:string|null}){const sql=database();try{const [row]=await sql<Row[]>`INSERT INTO app.duckdive_report_version(workspace_id,dive_id,version,source_hash,purpose_json,change_manifest_json,run_id) VALUES(${input.workspaceId}::uuid,${input.diveId},${input.version},${input.sourceHash},${sql.json(input.purpose as never)},${sql.json(input.manifest as never)},${input.runId??null}::uuid) ON CONFLICT(workspace_id,dive_id,version) DO UPDATE SET source_hash=excluded.source_hash,purpose_json=excluded.purpose_json,change_manifest_json=excluded.change_manifest_json,run_id=excluded.run_id RETURNING workspace_id,dive_id,version,source_hash,purpose_json,change_manifest_json,run_id,created_at`;return response(row);}finally{await sql.end();}}

export async function ensureStarterReportVersion(input:{userId:string;workspaceId:string;diveId:string;version:number;sourceHash:string;starterKey:string;title:string;description:string;contract:Parameters<typeof reportPurposeForStarter>[0]["contract"]}){const existing=await getDiveReportVersion(input.userId,input.diveId,input.version);if(existing)return existing;const purpose=reportPurposeForStarter({starterKey:input.starterKey,title:input.title,description:input.description,contract:input.contract});return saveDiveReportVersion({workspaceId:input.workspaceId,diveId:input.diveId,version:input.version,sourceHash:input.sourceHash,purpose,manifest:{request:"Starter report",interpretedIntent:purpose.goal,requested:{added:["Starter report"],changed:[],removed:[],unchanged:["Governed data contract"]},applied:{added:["Starter report"],changed:[],removed:[],unchanged:["Governed data contract"]},validations:[{id:"starter-contract",label:"Starter report matches the governed contract",status:"passed"}],version:input.version,generatedAt:new Date().toISOString()}});}
