import {useDiveState,useSQLQuery} from "@motherduck/react-sql-query";
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from "recharts";
const DD_THEME_CSS=String.raw`__DUCKDIVE_THEME_CSS__`;
const N=(v:unknown)=>v==null?0:Number(v);
export const REQUIRED_DATABASES=[{type:"share",path:"__MOTHERDUCK_SHARE_URL__",alias:"vic_house_data"}];
export default function VicMarketPulse(){
 const [suburb,setSuburb]=useDiveState("suburb","vic-yarraville");
 const [from,setFrom]=useDiveState("from","2016-01-01"),[to,setTo]=useDiveState("to","2026-07-18"),[bedroom,setBedroom]=useDiveState("bedrooms","all");
 const suburbs=useSQLQuery(`SELECT suburb_key,suburb FROM "vic_house_data"."main"."suburb_dimension" ORDER BY suburb`);
 const key=String(suburb).replaceAll("'","''"),start=String(from).replaceAll("'","''"),end=String(to).replaceAll("'","''"),bed=bedroom==='all'?"":bedroom==='7'?" AND bedrooms>=7":` AND bedrooms=${Math.max(1,Math.min(6,Number(bedroom)||1))}`;
 const summary=useSQLQuery(`SELECT count(*) sale_count,count(*) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) priced_sales,median(price_aud) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) median_price,avg(price_aud) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) average_price,median(land_size_sqm) FILTER(WHERE land_size_sqm BETWEEN __LAND_MIN__ AND __LAND_MAX__) median_land FROM "vic_house_data"."main"."suburb_sale_facts" WHERE suburb_key='${key}' AND sold_date BETWEEN DATE '${start}' AND DATE '${end}'${bed}`);
 const monthly=useSQLQuery(`SELECT strftime(date_trunc('month',sold_date),'%Y-%m') AS sale_month,count(*) AS sale_count,median(price_aud) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) AS median_price FROM "vic_house_data"."main"."suburb_sale_facts" WHERE suburb_key='${key}' AND sold_date BETWEEN DATE '${start}' AND DATE '${end}'${bed} GROUP BY 1 ORDER BY 1`);
 const s=Array.isArray(summary.data)?summary.data[0]:null,options=Array.isArray(suburbs.data)?suburbs.data:[],trend=(Array.isArray(monthly.data)?monthly.data:[]).map(r=>({month:String(r.sale_month),median:N(r.median_price),sales:N(r.sale_count)}));
 return <main className="dd-root p-6"><style>{DD_THEME_CSS}</style><div className="flex items-end justify-between mb-6"><div><p className="dd-kicker">Market</p><h1 className="text-3xl font-bold">Market Pulse</h1></div><select value={String(suburb)} onChange={e=>setSuburb(e.target.value)} className="dd-control p-2">{options.map((r:any)=><option key={String(r.suburb_key)} value={String(r.suburb_key)}>{String(r.suburb)}</option>)}</select></div><div className="grid grid-cols-3 gap-3 mb-8"><label className="text-xs">From<input type="date" value={String(from)} onChange={e=>setFrom(e.target.value)} className="dd-control block w-full p-2"/></label><label className="text-xs">To<input type="date" value={String(to)} onChange={e=>setTo(e.target.value)} className="dd-control block w-full p-2"/></label><label className="text-xs">Bedrooms<select value={String(bedroom)} onChange={e=>setBedroom(e.target.value)} className="dd-control block w-full p-2"><option value="all">All</option>{[1,2,3,4,5,6,7].map(v=><option key={v} value={String(v)}>{v===7?'7+':v}</option>)}</select></label></div><section className="grid grid-cols-4 gap-8 mb-8">{[["Sales",N(s?.sale_count).toLocaleString()], ["Priced sample",N(s?.priced_sales).toLocaleString()], ["Median",`$${N(s?.median_price).toLocaleString()}`],["Median land",`${N(s?.median_land).toLocaleString()} m²`]].map(([label,value])=><div key={label}><p className="text-4xl font-bold">{summary.isLoading?"—":value}</p><p className="dd-muted text-sm mt-2">{label}</p></div>)}</section><h2 className="text-lg font-semibold mb-3">Monthly Median Sale Price</h2>{monthly.isLoading?<div className="dd-loading h-64"/>:<ResponsiveContainer width="100%" height={260}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" stroke="var(--dd-line)"/><XAxis dataKey="month" fontSize={11}/><YAxis fontSize={11} tickFormatter={v=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={(v:any)=>`$${N(v).toLocaleString()}`}/><Line type="linear" dataKey="median" stroke="var(--dd-accent)" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer>}<p className="dd-muted text-xs mt-4">Unpriced sales count toward volume. Price statistics use reported prices from $50,000 to $20,000,000.</p></main>;
}
