import {useDiveState,useSQLQuery} from "@motherduck/react-sql-query";
const DD_THEME_CSS=String.raw`__DUCKDIVE_THEME_CSS__`;
const N=(v:unknown)=>v==null?0:Number(v);
export const REQUIRED_DATABASES=[{type:"share",path:"__MOTHERDUCK_SHARE_URL__",alias:"vic_house_data"}];
export default function MarketMatchup(){
 const [left,setLeft]=useDiveState("left-suburb","vic-yarraville"),[right,setRight]=useDiveState("right-suburb","vic-williamstown");
 const suburbs=useSQLQuery(`SELECT suburb_key,suburb FROM "vic_house_data"."main"."suburb_dimension" ORDER BY suburb`);
 const escaped=[left,right].map(v=>String(v).replaceAll("'","''"));
 const result=useSQLQuery(`SELECT d.suburb_key,d.suburb,count(*) sample_size,count(*) FILTER(WHERE f.price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) priced_sample,median(f.price_aud) FILTER(WHERE f.price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) median_price,median(f.land_size_sqm) FILTER(WHERE f.land_size_sqm BETWEEN __LAND_MIN__ AND __LAND_MAX__) median_land,count(*) FILTER(WHERE f.sold_date>=current_date-INTERVAL 1 YEAR) recent_sales FROM "vic_house_data"."main"."suburb_sale_facts" f JOIN "vic_house_data"."main"."suburb_dimension" d USING(suburb_key) WHERE f.suburb_key IN ('${escaped[0]}','${escaped[1]}') GROUP BY 1,2 ORDER BY 2`);
 const options=Array.isArray(suburbs.data)?suburbs.data:[],rows=Array.isArray(result.data)?result.data:[];
 const picker=(value:unknown,setter:(v:string)=>void)=><select value={String(value)} onChange={e=>setter(e.target.value)} className="dd-control p-2 w-full">{options.map((r:any)=><option key={String(r.suburb_key)} value={String(r.suburb_key)}>{String(r.suburb)}</option>)}</select>;
 return <main className="dd-root p-6"><style>{DD_THEME_CSS}</style><p className="dd-kicker">Compare</p><h1 className="text-3xl font-bold mb-8">Market Matchup</h1><div className="grid grid-cols-2 gap-6 mb-8">{picker(left,setLeft)}{picker(right,setRight)}</div><div className="grid grid-cols-2 gap-10">{rows.map((r:any)=><section className="dd-panel p-5" key={String(r.suburb_key)}><h2 className="text-2xl font-bold mb-5">{String(r.suburb)}</h2><dl className="grid grid-cols-2 gap-6"><div><dt className="dd-muted text-sm">Median Sale Price</dt><dd className="text-3xl font-bold mt-1">${N(r.median_price).toLocaleString()}</dd></div><div><dt className="dd-muted text-sm">Sales · 12 Months</dt><dd className="text-3xl font-bold mt-1">{N(r.recent_sales).toLocaleString()}</dd></div><div><dt className="dd-muted text-sm">Median Land</dt><dd className="text-2xl font-bold mt-1">{N(r.median_land).toLocaleString()} m²</dd></div><div><dt className="dd-muted text-sm">Priced Sample</dt><dd className="text-2xl font-bold mt-1">{N(r.priced_sample).toLocaleString()} <small>/ {N(r.sample_size).toLocaleString()}</small></dd></div></dl></section>)}</div>{result.isLoading?<div className="dd-loading h-40"/>:null}</main>;
}
