import {useSQLQuery} from "@motherduck/react-sql-query";
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from "recharts";
const DD_THEME_CSS=String.raw`__DUCKDIVE_THEME_CSS__`;
const N=(v:unknown)=>v==null?0:Number(v),D=(v:unknown)=>v==null?"—":String(v).slice(0,10);
export const REQUIRED_DATABASES=[{type:"share",path:"__MOTHERDUCK_SHARE_URL__",alias:"wa_vehicle_market"}];
export default function MarketMovement(){
 const movement=useSQLQuery(`SELECT * FROM "wa_vehicle_market"."contract"."market_movement" ORDER BY current_observed_at DESC LIMIT 1`);
 const events=useSQLQuery(`SELECT event_type,count(*) event_count FROM "wa_vehicle_market"."contract"."listing_events" WHERE comparison_basis='SNAPSHOT_INTERSECTION' GROUP BY event_type ORDER BY event_count DESC`);
 const m=Array.isArray(movement.data)?movement.data[0]:null,eventRows=(Array.isArray(events.data)?events.data:[]).map((r:any)=>({name:String(r.event_type).replaceAll("_"," ").toLowerCase(),count:N(r.event_count)}));
 const setDifferences=Boolean(m?.set_differences_available);
 return <main className="dd-root p-6"><style>{DD_THEME_CSS}</style><header className="mb-7"><p className="dd-kicker">Observed listing changes</p><h1 className="text-3xl font-bold">Market Movement</h1><p className="dd-muted text-xs mt-2">{D(m?.prior_observation_date)} → {D(m?.current_observation_date)} · same scope · matched listing IDs only</p></header><section className="grid grid-cols-4 gap-6 mb-8">{[["Matched listings",N(m?.matched_listing_count).toLocaleString()],["Asking price changed",N(m?.price_changed_count).toLocaleString()],["Price decreases",N(m?.price_decrease_count).toLocaleString()],["Price increases",N(m?.price_increase_count).toLocaleString()]].map(([label,value])=><div key={label}><p className="text-3xl font-bold">{movement.isLoading?"—":value}</p><p className="dd-muted text-xs mt-2">{label}</p></div>)}</section><section className="grid grid-cols-2 gap-8"><div><h2 className="font-semibold mb-3">Changes within the matched intersection</h2><ResponsiveContainer width="100%" height={280}><BarChart data={eventRows} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="var(--dd-line)"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={130} fontSize={10}/><Tooltip/><Bar dataKey="count" fill="var(--dd-accent)"/></BarChart></ResponsiveContainer></div><aside className="dd-panel p-5 text-sm"><h2 className="font-semibold">Population boundary</h2><p className="dd-muted mt-3">Prior snapshot: {N(m?.prior_listing_count).toLocaleString()} listings<br/>Current snapshot: {N(m?.current_listing_count).toLocaleString()} listings<br/>Median changed asking price: {m?.median_price_change==null?"—":`${N(m.median_price_change)>=0?"+":"−"}$${Math.abs(N(m.median_price_change)).toLocaleString()}`}</p><p className="mt-4">{setDifferences?`Newly observed: ${N(m?.newly_observed_count).toLocaleString()} · No longer observed: ${N(m?.no_longer_observed_count).toLocaleString()}`:"Newly observed and no-longer-observed counts are withheld because this pair is snapshot-comparable, not population-comparable."}</p></aside></section><p className="dd-muted text-xs mt-6">Changes describe repeated source listing IDs. Asking prices are not transactions, source absence does not prove sale, and snapshot totals must not be read as inflow or sell-through.</p></main>;
}
