import {useDiveState,useSQLQuery} from "@motherduck/react-sql-query";
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from "recharts";
const DD_THEME_CSS=String.raw`__DUCKDIVE_THEME_CSS__`;
const N=(v:unknown)=>v==null?0:Number(v);
export const REQUIRED_DATABASES=[{type:"share",path:"__MOTHERDUCK_SHARE_URL__",alias:"vic_house_data"}];
export default function SuburbStory(){
 const [suburb,setSuburb]=useDiveState("story-suburb","vic-footscray");
 const suburbs=useSQLQuery(`SELECT suburb_key,suburb FROM "vic_house_data"."main"."suburb_dimension" ORDER BY suburb`);
 const years=useSQLQuery(`SELECT year(sold_date) AS sale_year,count(*) AS sales,median(price_aud) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) AS median_price FROM "vic_house_data"."main"."suburb_sale_facts" WHERE suburb_key='${String(suburb).replaceAll("'","''")}' AND sold_date>=current_date-INTERVAL 8 YEAR GROUP BY 1 ORDER BY 1`);
 const bedrooms=useSQLQuery(`SELECT bedrooms,count(*) sample_size,count(*) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) priced_sample,median(price_aud) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) median_price FROM "vic_house_data"."main"."suburb_sale_facts" WHERE suburb_key='${String(suburb).replaceAll("'","''")}' AND bedrooms BETWEEN 2 AND 5 AND sold_date>=current_date-INTERVAL 5 YEAR GROUP BY 1 ORDER BY 1`);
 const options=Array.isArray(suburbs.data)?suburbs.data:[],annual=(Array.isArray(years.data)?years.data:[]).map(r=>({year:String(r.sale_year),sales:N(r.sales),median:N(r.median_price)})),beds=Array.isArray(bedrooms.data)?bedrooms.data:[];
 return <main className="dd-root p-6"><style>{DD_THEME_CSS}</style><header className="mb-6"><p className="dd-kicker">Place</p><div className="flex justify-between items-center"><h1 className="text-3xl font-bold">Suburb Story</h1><select value={String(suburb)} onChange={e=>setSuburb(e.target.value)} className="dd-control p-2">{options.map((r:any)=><option key={String(r.suburb_key)} value={String(r.suburb_key)}>{String(r.suburb)}</option>)}</select></div></header><section className="grid grid-cols-2 gap-8"><div><h2 className="font-semibold mb-3">Completed Sales by Year</h2>{years.isLoading?<div className="dd-loading h-64"/>:<ResponsiveContainer width="100%" height={260}><BarChart data={annual}><CartesianGrid strokeDasharray="3 3" stroke="var(--dd-line)"/><XAxis dataKey="year"/><YAxis/><Tooltip/><Bar dataKey="sales" fill="var(--dd-accent)"/></BarChart></ResponsiveContainer>}</div><div><h2 className="font-semibold mb-3">Bedroom Segments · 5 Years</h2><table className="w-full text-sm"><thead><tr className="text-left"><th className="py-2">Beds</th><th>Sales / Priced</th><th>Median</th></tr></thead><tbody>{beds.map((r:any)=><tr key={String(r.bedrooms)} className="dd-rule border-t"><td className="py-3">{N(r.bedrooms)}</td><td>{N(r.sample_size).toLocaleString()} / {N(r.priced_sample).toLocaleString()}</td><td>${N(r.median_price).toLocaleString()}</td></tr>)}</tbody></table><p className="dd-muted text-xs mt-5">Sales and priced samples are shown together.</p></div></section></main>;
}
