import {useDiveState,useSQLQuery} from "@motherduck/react-sql-query";
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from "recharts";
const N=(v:unknown)=>v==null?0:Number(v);
export const REQUIRED_DATABASES=[{type:"share",path:"__MOTHERDUCK_SHARE_URL__",alias:"vic_house_data"}];
export default function SuburbStory(){
 const [suburb,setSuburb]=useDiveState("story-suburb","vic-footscray");
 const suburbs=useSQLQuery(`SELECT suburb_key,suburb FROM "vic_house_data"."main"."suburb_dimension" ORDER BY suburb`);
 const years=useSQLQuery(`SELECT year(sold_date) AS sale_year,count(*) AS sales,median(price_aud) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) AS median_price FROM "vic_house_data"."main"."suburb_sale_facts" WHERE suburb_key='${String(suburb).replaceAll("'","''")}' AND sold_date>=current_date-INTERVAL 8 YEAR GROUP BY 1 ORDER BY 1`);
 const bedrooms=useSQLQuery(`SELECT bedrooms,count(*) sample_size,count(*) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) priced_sample,median(price_aud) FILTER(WHERE price_aud BETWEEN __PRICE_MIN__ AND __PRICE_MAX__) median_price FROM "vic_house_data"."main"."suburb_sale_facts" WHERE suburb_key='${String(suburb).replaceAll("'","''")}' AND bedrooms BETWEEN 2 AND 5 AND sold_date>=current_date-INTERVAL 5 YEAR GROUP BY 1 ORDER BY 1`);
 const options=Array.isArray(suburbs.data)?suburbs.data:[],annual=(Array.isArray(years.data)?years.data:[]).map(r=>({year:String(r.sale_year),sales:N(r.sales),median:N(r.median_price)})),beds=Array.isArray(bedrooms.data)?bedrooms.data:[];
 return <main className="p-6" style={{background:"#f8f8f8",color:"#231f20",minHeight:600}}><header className="mb-6"><p className="text-xs uppercase tracking-widest" style={{color:"#6a6a6a"}}>Suburb story</p><div className="flex justify-between items-center"><h1 className="text-3xl font-bold">Eight years in view</h1><select value={String(suburb)} onChange={e=>setSuburb(e.target.value)} className="p-2 border border-gray-300">{options.map((r:any)=><option key={String(r.suburb_key)} value={String(r.suburb_key)}>{String(r.suburb)}</option>)}</select></div></header><section className="grid grid-cols-2 gap-8"><div><h2 className="font-semibold mb-3">Completed sales by year</h2>{years.isLoading?<div className="h-64 bg-gray-200 animate-pulse"/>:<ResponsiveContainer width="100%" height={260}><BarChart data={annual}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year"/><YAxis/><Tooltip/><Bar dataKey="sales" fill="#0777b3"/></BarChart></ResponsiveContainer>}</div><div><h2 className="font-semibold mb-3">Bedroom segments · latest five years</h2><table className="w-full text-sm"><thead><tr className="text-left"><th className="py-2">Beds</th><th>Sales / priced</th><th>Median</th></tr></thead><tbody>{beds.map((r:any)=><tr key={String(r.bedrooms)} className="border-t border-gray-300"><td className="py-3">{N(r.bedrooms)}</td><td>{N(r.sample_size).toLocaleString()} / {N(r.priced_sample).toLocaleString()}</td><td>${N(r.median_price).toLocaleString()}</td></tr>)}</tbody></table><p className="text-xs mt-5" style={{color:"#6a6a6a"}}>Sales and valid priced samples are shown together so thin segments remain visible.</p></div></section></main>;
}
