import {useDiveState,useSQLQuery} from "@motherduck/react-sql-query";
const DD_THEME_CSS=String.raw`__DUCKDIVE_THEME_CSS__`;
const N=(v:unknown)=>v==null?0:Number(v),Q=(v:unknown)=>String(v).replaceAll("'","''");
export const REQUIRED_DATABASES=[{type:"share",path:"__MOTHERDUCK_SHARE_URL__",alias:"wa_vehicle_market"}];
export default function VehicleLens(){
 const [make,setMake]=useDiveState("lens-make","Subaru"),[model,setModel]=useDiveState("lens-model","Outback");
 const makes=useSQLQuery(`SELECT DISTINCT make FROM "wa_vehicle_market"."contract"."vehicle_market_current" WHERE make IS NOT NULL ORDER BY make`);
 const models=useSQLQuery(`SELECT DISTINCT model FROM "wa_vehicle_market"."contract"."vehicle_market_current" WHERE make='${Q(make)}' AND model IS NOT NULL ORDER BY model`);
 const rows=useSQLQuery(`SELECT listing_key,manufacturer_year,make,model,variant,advertised_price,odometer_km,listing_age_days,cohort_size,cohort_median_asking_price,cohort_p25_asking_price,cohort_p75_asking_price,asking_price_percentile,prior_observed_price,observed_price_change,last_change_observed_at FROM "wa_vehicle_market"."contract"."vehicle_screen" WHERE make='${Q(make)}' AND model='${Q(model)}' ORDER BY manufacturer_year DESC,advertised_price LIMIT 100`);
 const data=Array.isArray(rows.data)?rows.data:[],makeOptions=Array.isArray(makes.data)?makes.data:[],modelOptions=Array.isArray(models.data)?models.data:[];
 return <main className="dd-root p-6"><style>{DD_THEME_CSS}</style><header className="mb-6"><p className="dd-kicker">Transparent peer evidence</p><h1 className="text-3xl font-bold">Vehicle Lens</h1></header><section className="grid grid-cols-2 gap-3 mb-6"><label className="text-xs">Make<select className="dd-control block w-full p-2" value={String(make)} onChange={e=>setMake(e.target.value)}>{makeOptions.map((r:any)=><option key={String(r.make)}>{String(r.make)}</option>)}</select></label><label className="text-xs">Model<select className="dd-control block w-full p-2" value={String(model)} onChange={e=>setModel(e.target.value)}>{modelOptions.map((r:any)=><option key={String(r.model)}>{String(r.model)}</option>)}</select></label></section><div className="overflow-auto"><table className="w-full text-xs"><thead><tr className="text-left"><th className="py-2">Vehicle</th><th>Asking</th><th>Observed change</th><th>Odometer</th><th>Listing age</th><th>Cohort</th><th>Cohort median / range</th><th>Percentile</th></tr></thead><tbody>{data.map((r:any)=><tr key={String(r.listing_key)} className="dd-rule border-t"><td className="py-3"><strong>{N(r.manufacturer_year)} {String(r.make)} {String(r.model)}</strong><br/><span className="dd-muted">{String(r.variant??"")}</span></td><td>${N(r.advertised_price).toLocaleString()}</td><td>{r.observed_price_change==null?"—":`${N(r.observed_price_change)>=0?"+":"−"}$${Math.abs(N(r.observed_price_change)).toLocaleString()}`}<br/><span className="dd-muted">{r.prior_observed_price==null?"No matched price change":`from $${N(r.prior_observed_price).toLocaleString()}`}</span></td><td>{N(r.odometer_km).toLocaleString()} km<br/><span className="dd-muted">{N(r.odometer_km)/Math.max(1,new Date().getFullYear()-N(r.manufacturer_year))|0} km/year</span></td><td>{N(r.listing_age_days)} days</td><td>{N(r.cohort_size)}</td><td>{N(r.cohort_size)<10?"Insufficient sample":`$${N(r.cohort_median_asking_price).toLocaleString()} · $${N(r.cohort_p25_asking_price).toLocaleString()}–$${N(r.cohort_p75_asking_price).toLocaleString()}`}</td><td>{r.asking_price_percentile==null?"—":`${Math.round(N(r.asking_price_percentile)*100)}th`}</td></tr>)}</tbody></table></div><p className="dd-muted text-xs mt-5">Cohorts use the same make and model within ±2 manufacturer years. Observed changes compare the same listing ID across snapshot-comparable observations; they are not transaction prices.</p></main>;
}
