import {useDiveState,useSQLQuery} from "@motherduck/react-sql-query";
import {BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from "recharts";
const DD_THEME_CSS=String.raw`__DUCKDIVE_THEME_CSS__`;
const N=(v:unknown)=>v==null?0:Number(v),Q=(v:unknown)=>String(v).replaceAll("'","''");
export const REQUIRED_DATABASES=[{type:"share",path:"__MOTHERDUCK_SHARE_URL__",alias:"wa_vehicle_market"}];
export default function VehicleMarketAtlas(){
 const [make,setMake]=useDiveState("atlas-make","All");
 const makes=useSQLQuery(`SELECT DISTINCT make FROM "wa_vehicle_market"."contract"."vehicle_market_current" WHERE make IS NOT NULL ORDER BY make`);
 const where=make==="All"?"":` WHERE make='${Q(make)}'`;
 const summary=useSQLQuery(`SELECT count(*) listing_count,count(advertised_price) priced_count,median(advertised_price) median_price,median(odometer_km) median_odometer,min(observed_at) observed_at FROM "wa_vehicle_market"."contract"."vehicle_market_current"${where}`);
 const makeRows=useSQLQuery(`SELECT make,count(*) listing_count,median(advertised_price) FILTER(WHERE advertised_price IS NOT NULL) median_price FROM "wa_vehicle_market"."contract"."vehicle_market_current"${where} GROUP BY make ORDER BY listing_count DESC LIMIT 15`);
 const priceRows=useSQLQuery(`SELECT floor(advertised_price/5000)*5000 price_band,count(*) listing_count FROM "wa_vehicle_market"."contract"."vehicle_market_current"${where}${where?" AND":" WHERE"} advertised_price BETWEEN 0 AND 150000 GROUP BY 1 ORDER BY 1`);
 const odometerRows=useSQLQuery(`SELECT floor(odometer_km/25000)*25000 odometer_band,count(*) listing_count FROM "wa_vehicle_market"."contract"."vehicle_market_current"${where}${where?" AND":" WHERE"} odometer_km BETWEEN 0 AND 500000 GROUP BY 1 ORDER BY 1`);
 const timeseries=useSQLQuery(`SELECT observation_date,listing_count,median_asking_price FROM "wa_vehicle_market"."contract"."market_timeseries" ORDER BY observed_at`);
 const s=Array.isArray(summary.data)?summary.data[0]:null,options=Array.isArray(makes.data)?makes.data:[],byMake=(Array.isArray(makeRows.data)?makeRows.data:[]).map((r:any)=>({name:String(r.make),listings:N(r.listing_count)})),prices=(Array.isArray(priceRows.data)?priceRows.data:[]).map((r:any)=>({band:`$${N(r.price_band)/1000}k`,listings:N(r.listing_count)})),odometers=(Array.isArray(odometerRows.data)?odometerRows.data:[]).map((r:any)=>({band:`${N(r.odometer_band)/1000}k`,listings:N(r.listing_count)})),observations=(Array.isArray(timeseries.data)?timeseries.data:[]).map((r:any)=>({date:String(r.observation_date).slice(0,10),listings:N(r.listing_count)}));
 const Chart=({data,label}:{data:any[];label:string})=><div><h2 className="font-semibold mb-3">{label}</h2><ResponsiveContainer width="100%" height={240}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="var(--dd-line)"/><XAxis dataKey={data===byMake?"name":"band"} fontSize={10}/><YAxis/><Tooltip/><Bar dataKey="listings" fill="var(--dd-accent)"/></BarChart></ResponsiveContainer></div>;
 return <main className="dd-root p-6"><style>{DD_THEME_CSS}</style><header className="flex items-end justify-between mb-7"><div><p className="dd-kicker">Current observation</p><h1 className="text-3xl font-bold">Market Atlas</h1></div><select className="dd-control p-2" value={String(make)} onChange={e=>setMake(e.target.value)}><option>All</option>{options.map((r:any)=><option key={String(r.make)}>{String(r.make)}</option>)}</select></header><section className="grid grid-cols-4 gap-6 mb-8">{[["Listings",N(s?.listing_count).toLocaleString()],["Priced sample",N(s?.priced_count).toLocaleString()],["Median asking",`$${N(s?.median_price).toLocaleString()}`],["Median odometer",`${N(s?.median_odometer).toLocaleString()} km`]].map(([label,value])=><div key={label}><p className="text-3xl font-bold">{summary.isLoading?"—":value}</p><p className="dd-muted text-xs mt-2">{label}</p></div>)}</section><section className="grid grid-cols-1 gap-8"><Chart data={byMake} label="Listings by make"/><div className="grid grid-cols-2 gap-8"><Chart data={prices} label="Asking-price distribution · $5k bands"/><Chart data={odometers} label="Odometer distribution · 25k km bands"/></div><div><h2 className="font-semibold mb-3">Observed snapshot counts</h2><ResponsiveContainer width="100%" height={220}><LineChart data={observations}><CartesianGrid strokeDasharray="3 3" stroke="var(--dd-line)"/><XAxis dataKey="date" fontSize={10}/><YAxis domain={["dataMin - 100","dataMax + 100"]}/><Tooltip/><Line type="monotone" dataKey="listings" stroke="var(--dd-accent)" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section><p className="dd-muted text-xs mt-5">Asking prices are not transaction prices. Snapshot counts are observation points, not inflow, sell-through, or evidence of sale.</p></main>;
}
