"use client";
/* eslint-disable @next/next/no-html-link-for-pages, react-hooks/refs, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {useChat} from "@ai-sdk/react";import {DefaultChatTransport,isToolUIPart,getToolName} from "ai";import {FormEvent,useEffect,useMemo,useRef,useState} from "react";import {useRouter,useSearchParams} from "next/navigation";
const STARTERS=[{key:"market-pulse",label:"Market Pulse"},{key:"suburb-story",label:"Suburb Story"},{key:"market-matchup",label:"Matchup"}];
type DiveShare={id:string;slug:string;url:string;viewCount:number;createdAt:string};
export default function EditLab(){const router=useRouter(),params=useSearchParams(),[diveIds,setDiveIds]=useState<Record<string,string>>({}),[activeKey,setActiveKey]=useState(params.get("key")||"market-pulse"),[embed,setEmbed]=useState(""),[input,setInput]=useState(""),[error,setError]=useState(""),[version,setVersion]=useState<number|null>(null),[reverting,setReverting]=useState(false),[share,setShare]=useState<DiveShare|null>(null),[shareStatus,setShareStatus]=useState(""),[sharing,setSharing]=useState(false),activeId=diveIds[activeKey],activeRef=useRef<string|undefined>(activeId),chatRef=useRef(crypto.randomUUID());activeRef.current=activeId;
 const transport=useMemo(()=>new DefaultChatTransport({api:"/api/chat",body:()=>({activeDiveId:activeRef.current,chatId:chatRef.current})}),[]);const {messages,sendMessage,status,stop}=useChat({transport,id:chatRef.current});const busy=status==="submitted"||status==="streaming";
 async function loadShare(id:string){const response=await fetch(`/api/dives/${id}/share`,{cache:"no-store"});const body=await response.json();if(response.ok)setShare(body.share||null);}
 async function refresh(id=activeRef.current){if(!id)return;const response=await fetch(`/api/dives/${id}/embed`,{cache:"no-store"});if(response.status===401){router.replace(`/login?next=${encodeURIComponent(`/edit?key=${activeKey}`)}`);return;}const body=await response.json();if(!response.ok){setError(body.error||"Embed unavailable");return;}setEmbed(body.session);const v=await fetch(`/api/dives/${id}/version`,{cache:"no-store"}).then(r=>r.json());setVersion(Number(v.version)||null);await loadShare(id);}
 useEffect(()=>{fetch("/api/edit",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}).then(async response=>{if(response.status===401){router.replace(`/login?next=${encodeURIComponent(`/edit?key=${activeKey}`)}`);return null;}const body=await response.json();if(!response.ok)throw new Error(body.error||"Workspace unavailable");return body;}).then(body=>{if(body)setDiveIds(body.diveIds);}).catch(reason=>setError(reason.message));},[router]);
 useEffect(()=>{if(activeId){setEmbed("");setError("");setShare(null);setShareStatus("");refresh(activeId);}},[activeId]);
 const previousStatus=useRef(status);useEffect(()=>{if(previousStatus.current==="streaming"&&status==="ready")refresh();previousStatus.current=status;},[status]);
 function submit(event:FormEvent){event.preventDefault();if(!input.trim()||busy||!activeId)return;sendMessage({text:input.trim()});setInput("");}
 async function revert(){if(!activeId||!version||version<=1)return;setReverting(true);const response=await fetch(`/api/dives/${activeId}/revert`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:version-1})});if(response.ok)await refresh(activeId);else setError((await response.json()).error||"Revert failed");setReverting(false);}
 async function publish(){if(!activeId||sharing)return;setSharing(true);setShareStatus("");const response=await fetch(`/api/dives/${activeId}/share`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}),body=await response.json();if(!response.ok){setShareStatus(body.error||"Could not publish link");setSharing(false);return;}setShare(body.share);try{await navigator.clipboard.writeText(body.share.url);setShareStatus("Published · link copied");}catch{setShareStatus("Published · copy link when ready");}setSharing(false);}
 async function copyShare(){if(!share)return;try{await navigator.clipboard.writeText(share.url);setShareStatus("Link copied");}catch{setShareStatus(share.url);}}
 async function revokeShare(){if(!activeId||!share||sharing||!window.confirm("Revoke this public link? Anyone using it will lose access immediately."))return;setSharing(true);const response=await fetch(`/api/dives/${activeId}/share`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:"{}"});if(response.ok){setShare(null);setShareStatus("Link revoked");}else setShareStatus((await response.json()).error||"Could not revoke link");setSharing(false);}
 return <main className="edit-lab"><header className="lab-header"><a href="/" className="lab-brand"><span className="lab-duck">D</span><span>DUCKDIVE <i>GOLD</i></span></a><div className="edit-tabs">{STARTERS.map(item=><button key={item.key} className={activeKey===item.key?"active":""} onClick={()=>setActiveKey(item.key)}>{item.label}</button>)}</div><a href="/">Exit editor</a></header><div className="edit-grid"><section className="edit-canvas"><div className="edit-toolbar"><span><i/> Live preview {version?`· v${version}`:""}{shareStatus?` · ${shareStatus}`:share?` · shared · ${share.viewCount} views`:""}</span><div>{share?<><button disabled={sharing} onClick={copyShare}>Copy link</button><button disabled={sharing} onClick={revokeShare}>Revoke link</button></>:<button disabled={!activeId||sharing} onClick={publish}>{sharing?"Publishing…":"Publish link"}</button>}<button onClick={()=>refresh()}>Refresh</button><button disabled={!version||version<=1||reverting} onClick={revert}>{reverting?"Reverting…":"Revert one version"}</button></div></div>{error?<div className="lab-error">{error}</div>:embed?<iframe key={embed} title="Editable Dive" src={`https://embed-motherduck.com/sandbox/#session=${embed}`} sandbox="allow-scripts allow-same-origin"/>:<div className="lab-loading">Preparing your private workspace…</div>}</section><aside className="chat-panel"><header><div><p>AI Dive editor</p><h2>Remix this view</h2></div><span>✦</span></header><div className="chat-messages">{!messages.length&&<div className="chat-welcome"><strong>Ask for a focused change.</strong><p>I can inspect the VIC estate and edit only this Dive.</p>{["Add a date-range control","Compare the latest year with the previous year","Make sample sizes more prominent"].map(value=><button key={value} onClick={()=>setInput(value)}>{value}</button>)}</div>}{messages.map(message=><div key={message.id} className={`chat-message ${message.role}`}>{message.parts.map((part,index)=>part.type==="text"?<p key={index}>{part.text}</p>:isToolUIPart(part)?<small key={index}>↳ {getToolName(part).replaceAll("_"," ")}</small>:null)}</div>)}{busy&&<div className="chat-thinking">Working through the data…</div>}</div><form onSubmit={submit}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Describe one change…" maxLength={1000}/><div><span>{input.trim().split(/\s+/).filter(Boolean).length}/100 words</span>{busy?<button type="button" onClick={stop}>Stop</button>:<button disabled={!input.trim()||!activeId}>Send ↗</button>}</div></form></aside></div></main>}
